services:
  - type: web
    name: sasto-bazar
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
